define([
    "jquery"
  , "lib/util/template"
  , "config/charts"
  , "lib/model/exports/datasource2load"
  , "text!templates/html.chart.export.html"
],

function($, template, charts, datasource2load, tplHtml) {
  return function(chart, options) {
    var chart_options = $.extend({}, {width:500,height:250}, chart.options)
    var params = {
            title      : "ReportGrid Chart - Generated by The Builder"
          , chart_type : charts.map[chart.type].method
          , axes       : JSON.stringify(chart.axes)
          , options    : JSON.stringify(chart_options, null, 2)
          , load       : datasource2load(chart.datasource)
//          , script     : JSON.stringify(chart, null, 2)
        };
    return template(tplHtml, params);
  };
});