define([
    "lib/util/template"
  , "config/charts"
  , "text!templates/html.chart.export.html"
],

function(template, charts, tplHtml) {
  return function(chart, options) {
    var params = {
          title   : "ReportGrid Chart - Generated by The Builder",
          chart_type : charts.map[chart.type].method,
          axes    : JSON.stringify(chart.axes),
          options : JSON.stringify(chart.options, null, 2),
          script  : JSON.stringify(chart, null, 2)
        };
    return template(tplHtml, params);
  };
});